In [1]:
import numpy as np

In [2]:
A = np.random.randn(2,3)
A

array([[ 0.5213099 , -1.43406949,  0.38217535],
       [-0.07441345,  1.23187687, -0.9457791 ]])

In [3]:

A.sum(axis=1)



array([-0.53058425,  0.21168432])

In [4]:
A.sum(axis=0)

array([ 0.44689645, -0.20219263, -0.56360375])

In [5]:
A.cumsum(axis=1)

array([[ 0.5213099 , -0.9127596 , -0.53058425],
       [-0.07441345,  1.15746342,  0.21168432]])

In [6]:
A.argmin(axis=0)

array([1, 0, 1])

In [7]:
np.exp(A)

array([[1.68423238, 0.23833703, 1.46546903],
       [0.92828781, 3.42765676, 0.38837687]])

In [8]:
A.mean()

-0.05314998786830385

In [9]:
A.var()

0.8124973118530833

In [16]:
A.std()

0.9633643737089718

In [18]:
np.corrcoef(A)[0,1]

-0.716207509162587

In [19]:
np.unique(A, return_counts=True)

(array([-2.25268705, -0.96644772, -0.75423212, -0.02313592,  0.45120649,
         0.54024866]),
 array([1, 1, 1, 1, 1, 1]))

In [20]:
np.random.seed(0)
A = np.random.randint(0,10,[5,5])
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [21]:
v, c = np.unique(A, return_counts=True)
c

array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3])

In [22]:
for i ,j in zip(v[c.argsort()], c[c.argsort()]):
    print(f'valeur {i} apparaît {j} fois')

valeur 0 apparaît 1 fois
valeur 2 apparaît 1 fois
valeur 1 apparaît 2 fois
valeur 4 apparaît 2 fois
valeur 6 apparaît 2 fois
valeur 3 apparaît 3 fois
valeur 5 apparaît 3 fois
valeur 9 apparaît 3 fois
valeur 7 apparaît 4 fois
valeur 8 apparaît 4 fois


In [44]:
    np.random.seed(0)
    A = np.random.randint(0,100, [10,5])
    A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [45]:
A_norm = (A-A.mean(axis=0))/(A.std(axis=0))

In [46]:
A_norm

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])